import java.util.Scanner;

/**
 * Main class to run the Library Management System
 * Version 3.0 (MySQL-powered)
 * Author: Shankz
 */

class Main {

    public static void main(String[] args) {

        Library library = new Library();
        Scanner scanner = new Scanner(System.in);

        int choice = 0;

        while (choice != 9) {

            System.out.println("\nWelcome to the Library Management System!");
            System.out.println("1. Add a book");
            System.out.println("2. Add a student");
            System.out.println("3. Borrow a book");
            System.out.println("4. Return a book");
            System.out.println("5. Display all borrowed books");
            System.out.println("6. Display all students");
            System.out.println("7. Display all books");
            System.out.println("8. Search");
            System.out.println("9. Exit");

            System.out.print("Enter your choice: ");
            choice = scanner.nextInt();
            scanner.nextLine(); // consume newline

            switch (choice) {

                case 1:
                    System.out.print("Enter book title: ");
                    String title = scanner.nextLine();

                    System.out.print("Enter author name: ");
                    String author = scanner.nextLine();

                    // Book ID is auto-generated by MySQL now
                    library.addBook(new Book(0, title, author));
                    break;

                case 2:
                    System.out.print("Enter student name: ");
                    String studentName = scanner.nextLine();

                    // Student ID is auto-generated by MySQL now
                    library.addStudent(new Student(0, studentName));
                    break;

                case 3:
                    System.out.print("Enter student ID: ");
                    int sId = scanner.nextInt();
                    scanner.nextLine();

                    System.out.print("Enter book ID: ");
                    int bId = scanner.nextInt();
                    scanner.nextLine();

                    library.borrowBook(sId, bId);
                    break;

                case 4:
                    System.out.print("Enter student ID: ");
                    int sId2 = scanner.nextInt();
                    scanner.nextLine();

                    System.out.print("Enter book ID: ");
                    int bId2 = scanner.nextInt();
                    scanner.nextLine();

                    library.returnBook(sId2, bId2);
                    break;

                case 5:
                    library.displayAllBorrowedBooks();
                    break;

                case 6:
                    library.displayAllStudents();
                    break;

                case 7:
                    library.displayAllBooks();
                    break;

                case 8:
                    System.out.println("\nSearch by:");
                    System.out.println("1. Book Title");
                    System.out.println("2. Student Name");
                    System.out.println("3. Book ID");
                    System.out.print("Enter choice: ");

                    int searchChoice = scanner.nextInt();
                    scanner.nextLine();

                    switch (searchChoice) {
                        case 1:
                            System.out.print("Enter book title: ");
                            String titleSearch = scanner.nextLine();
                            library.searchBookByTitle(titleSearch);
                            break;

                        case 2:
                            System.out.print("Enter student name: ");
                            String studentSearch = scanner.nextLine();
                            library.searchStudent(studentSearch);
                            break;

                        case 3:
                            System.out.print("Enter book ID: ");
                            int bookIdSearch = scanner.nextInt();
                            scanner.nextLine();
                            library.searchBookById(bookIdSearch);
                            break;

                        default:
                            System.out.println("Invalid search option.");
                    }
                    break;

                case 9:
                    System.out.println("...Goodbye!...");
                    break;

                default:
                    System.out.println("Invalid choice. Please try again.");
            }
        }

        scanner.close();
    }
}
